@testable import SpotiStats
import XCTest

final class DateExtensionsTests: XCTestCase {
    // MARK: - relativeDisplay

        func testJustNow() {
                let now = Date()
                        XCTAssertEqual(now.relativeDisplay(relativeTo: now), "Just now")
                            }

                                func testMinutesAgo() {
                                        let now = Date()
                                                let fiveMinAgo = now.addingTimeInterval(-5 * 60)
                                                        XCTAssertEqual(fiveMinAgo.relativeDisplay(relativeTo: now), "5 min ago")
                                                            }

                                                                func testOneMinuteAgo() {
                                                                        let now = Date()
                                                                                let oneMinAgo = now.addingTimeInterval(-60)
                                                                                        XCTAssertEqual(oneMinAgo.relativeDisplay(relativeTo: now), "1 min ago")
                                                                                            }

                                                                                                func testHoursAgo() {
                                                                                                        let now = Date()
                                                                                                                let threeHoursAgo = now.addingTimeInterval(-3 * 3_600)
                                                                                                                        XCTAssertEqual(threeHoursAgo.relativeDisplay(relativeTo: now), "3 hours ago")
                                                                                                                            }
                                                                                                                            
                                                                                                                                func testOneHourAgo() {
                                                                                                                                        let now = Date()
                                                                                                                                                let oneHourAgo = now.addingTimeInterval(-3_600)
                                                                                                                                                        XCTAssertEqual(oneHourAgo.relativeDisplay(relativeTo: now), "1 hour ago")
                                                                                                                                                            }
                                                                                                                                                            
                                                                                                                                                                func testYesterday() {
                                                                                                                                                                        let now = Date()
                                                                                                                                                                                let yesterday = now.addingTimeInterval(-24 * 3_600)
                                                                                                                                                                                        XCTAssertEqual(yesterday.relativeDisplay(relativeTo: now), "Yesterday")
                                                                                                                                                                                            }
                                                                                                                                                                                            
                                                                                                                                                                                                func testDaysAgo() {
                                                                                                                                                                                                        let now = Date()
                                                                                                                                                                                                                let fourDaysAgo = now.addingTimeInterval(-4 * 24 * 3_600)
                                                                                                                                                                                                                        XCTAssertEqual(fourDaysAgo.relativeDisplay(relativeTo: now), "4 days ago")
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                func testFutureDateReturnsJustNow() {
                                                                                                                                                                                                                                        let now = Date()
                                                                                                                                                                                                                                                let future = now.addingTimeInterval(3_600)
                                                                                                                                                                                                                                                        XCTAssertEqual(future.relativeDisplay(relativeTo: now), "Just now")
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                // MARK: - startOfDay / startOfWeek / startOfMonth
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                    func testStartOfDayIsMidnight() {
                                                                                                                                                                                                                                                                            let date = Date()
                                                                                                                                                                                                                                                                                    let startOfDay = date.startOfDay
                                                                                                                                                                                                                                                                                            let components = Calendar.current.dateComponents([.hour, .minute, .second], from: startOfDay)
                                                                                                                                                                                                                                                                                                    XCTAssertEqual(components.hour, 0)
                                                                                                                                                                                                                                                                                                            XCTAssertEqual(components.minute, 0)
                                                                                                                                                                                                                                                                                                                    XCTAssertEqual(components.second, 0)
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                            func testStartOfMonthIsFirstDay() {
                                                                                                                                                                                                                                                                                                                                    let date = Date()
                                                                                                                                                                                                                                                                                                                                            let startOfMonth = date.startOfMonth
                                                                                                                                                                                                                                                                                                                                                    let day = Calendar.current.component(.day, from: startOfMonth)
                                                                                                                                                                                                                                                                                                                                                            XCTAssertEqual(day, 1)
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                    // MARK: - isSameDay / isSameWeek
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                        func testSameDayReturnsTrue() {
                                                                                                                                                                                                                                                                                                                                                                                let now = Date()
                                                                                                                                                                                                                                                                                                                                                                                        let later = now.addingTimeInterval(3_600)
                                                                                                                                                                                                                                                                                                                                                                                                XCTAssertTrue(now.isSameDay(as: later))
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        func testDifferentDayReturnsFalse() {
                                                                                                                                                                                                                                                                                                                                                                                                                let now = Date()
                                                                                                                                                                                                                                                                                                                                                                                                                        let twoDaysLater = now.addingTimeInterval(2 * 24 * 3_600)
                                                                                                                                                                                                                                                                                                                                                                                                                                XCTAssertFalse(now.isSameDay(as: twoDaysLater))
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                        // MARK: - periodLabel
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                            func testTodayPeriodLabel() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    let now = Date()
                                                                                                                                                                                                                                                                                                                                                                                                                                                            XCTAssertEqual(now.periodLabel(relativeTo: now), "Today")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    func testYesterdayPeriodLabel() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let now = Date()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let yesterday = Calendar.current.date(byAdding: .day, value: -1, to: now)!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            XCTAssertEqual(yesterday.periodLabel(relativeTo: now), "Yesterday")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // MARK: - iso8601String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        func testISO8601StringContainsT() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let isoString = Date().iso8601String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        XCTAssertTrue(isoString.contains("T"), "ISO 8601 string should contain 'T' separator")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                func testISO8601StringContainsFractionalSeconds() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let isoString = Date().iso8601String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                XCTAssertTrue(isoString.contains("."), "ISO 8601 string should contain fractional seconds")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
